---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: metallb
  namespace: flux-system
spec:
  chart:
    spec:
      chart: metallb
      sourceRef:
        kind: HelmRepository
        name: metallb
      interval: 1m
      version: "0.13.9"
  interval: 1m0s
  targetNamespace: metallb-system
  install:
    remediation:
      retries: -1
  upgrade:
    remediation:
      retries: -1
  # values: