---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: ks-addons-install
  namespace: flux-system
spec:
  path: "./clusters/titania/addons/install"
  interval: 10m0s
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  dependsOn:
    - name: ks-utilities-install
