---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: ks-flux-cd
  namespace: flux-system
spec:
  path: "./base/fluxcd"
  interval: 10m0s
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
