---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: ks-post-utils-secrets
  namespace: flux-system
spec:
  decryption:
    provider: sops
    secretRef:
      name: sops-gpg
  path: "./clusters/titania/secrets/post-utils"
  interval: 10m0s
  prune: true
  suspend: false
  sourceRef:
    kind: GitRepository
    name: flux-system
  dependsOn:
    - name: ks-utilities-install
