---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: ks-pre-utils-secrets
  namespace: flux-system
spec:
  decryption:
    provider: sops
    secretRef:
      name: sops-gpg
  path: "./clusters/titania/secrets/pre-utils"
  interval: 10m0s
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
