---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: ks-addon-step-issuer
  namespace: flux-system
spec:
  decryption:
    provider: sops
    secretRef:
      name: sops-gpg
  interval: 5m
  path: "./addons/smallstep-issuer"
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  healthChecks:
  - apiVersion: apps/v1
    kind: Deployment
    name: step-issuer
    namespace: cert-manager
  dependsOn:
    - name: ks-utilities-cert-manager
