---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: ks-utilities-metallb
  namespace: flux-system
spec:
  path: "./utilities/metallb"
  interval: 10m0s
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  healthChecks:
  - apiVersion: apps/v1
    kind: Deployment
    name: metallb-system-metallb-controller
    namespace: metallb-system
  - apiVersion: apps/v1
    kind: DaemonSet
    name: metallb-system-metallb-speaker
    namespace: metallb-system
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: ks-utilities-metallb-config
  namespace: flux-system
spec:
  path: "./clusters/titania/utilities/metallb"
  interval: 10m0s
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  dependsOn:
    - name: ks-utilities-metallb
