---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: ks-utilities-metallb-config
  namespace: flux-system
spec:
  path: "./clusters/titania/utilities/metallb"
  interval: 10m0s
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  dependsOn:
  - name: ks-utilities-metallb
