---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: ks-utilities-cert-manager-config
  namespace: flux-system
spec:
  path: "./clusters/titania/utilities/cert-manager"
  interval: 10m0s
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  dependsOn:
  - name: ks-utilities-cert-manager
