---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: ks-utilities-coredns
  namespace: flux-system
spec:
  path: "./utilities/coredns"
  interval: 10m0s
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  healthChecks:
  - apiVersion: apps/v1
    kind: Deployment
    name: coredns
    namespace: kube-system
