apiVersion: v1
kind: Secret
metadata:
    name: step-issuer-derpy
    namespace: cert-manager
type: Opaque
stringData:
    pass: ENC[AES256_GCM,data:IllFdFBfJurOQFDq470NH0oNwxCNjrdvMmUjDJh8Y0U=,iv:nSPCGA5FDY0lKOuV8F8BTIx8sPCeU9r/CKjd+ft07xk=,tag:I4/mXCbgaqVCOQDKv95zSQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2023-05-09T09:41:37Z"
    mac: ENC[AES256_GCM,data:v0Q5Ly2M41NJn07OrDoxo9MDehqXWWczqONtuGNXuJ7Pxte0yAFyyP4hpTB7nHtVfJpFNv3tWiD4oY9cAXh4Bu2ip7E7+FB7QZgxMKPlh2PoU2CAHBYBPG248OPVokIisNS9d8nNCK4lIgr9pUqabvNsm9ZS0FnIUUN1EYqEXrs=,iv:dViBBZPhV599Q0lqDTUlxqtkWAxQTxm7kSKDAluKKgs=,tag:3XSYvCa9Y/+gKgqWnUfAPw==,type:str]
    pgp:
        - created_at: "2023-05-09T09:41:37Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA+C44NfmdMwmAQ//cBJmYk1B7DzImyi34n5GwU0aY86VTqTynfE4Tp8wEpKf
            dfk1A31BrS+hVZBertq9TggyAwnbtn2WknIhQv1LZSfZybE4uNkQIFJREh4DzTOZ
            44+41J/zteP16oD7ssSV3wKXYr19T99cgbguchFNTNHGeutVp/c+2dGmPuYHFFgV
            zaU9TWZ6umIDMLHj3CwR+RDg+bNisS2uI686o9t/u7gNc9Vl1rpzTOq8TdB9JiSQ
            1a6l5HDbM1BqElLvQ0AAYEm5BnKsnBLrG4qPxrN0+LZDuHpF3JrGYjHqyG+fpke3
            EsbA2vsu+A3Rdhg4TgN5MPG9QiXiaK/1LK8C5oG88Mxr76x2rFL+1bFaUp+6p8oZ
            E+6ZtRY5+jVwQ1vcPosIAKqUA/BsXaQaxR27vk1HUpS7lob9n59obarc6TaK3HJC
            HbevbW3nzb7OZO+0jINHJ76j9YjakIz0RtZCbEbAA5iOmhGnxU2ZTbmzrSmZcPXc
            OOEELSJbJt9gndyc5M99r8Ujkrd5l+V/NK8zubSiUXKOZQW5q4g4qqLdko4tJyQN
            UJYetXkBO495hxBH8OhJ8AE3kRol8wWzFjz/OMzqqVP4abav6EH0mb24pUEQylu0
            +NbNfd14eRnzpJ4C1saxI4AY76p3uSAMdMTWsePbOL83pINnBqKYtBQdHwLR7b/S
            XAHpnOSE1DbpeyiEWCj1lOcK42Irvv20sjicjG+VzOTN9kLuu5q+IieU9WGpDNNz
            /Q/fK+R94E96h1y6ChAi8Uu2NrLwdatU8Q4HdKaB4EFBijzRA0pzaO8KGoMt
            =70Zz
            -----END PGP MESSAGE-----
          fp: B270E03084957BDD7272F1CB5C30E63DCE53ED08
        - created_at: "2023-05-09T09:41:37Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hF4DV/s3aZyXgOMSAQdAfbp/F65+4PMmovmSN5HyrKBwBugK80WxxfSmQqvKnFIw
            vlo79cVuEBqF88SY05zF/B9QCnI7cUIotCSH+yiXFCBwJiVU42V1JWQXz7RopcS8
            0lwBo06vHSKcyBhyVHRCu08ms3pVW6+r7gVeJK6Klw3ukABxaEve6ff10v5uhzvA
            C3s1B89NC3Rcx7T2d/Ejamiww4eATh3TCim8k5qd35aSvzkCuW+t7T/tZiKsFA==
            =7W4v
            -----END PGP MESSAGE-----
          fp: 71DADA7922B3E08101B3341369C476704F97DBDA
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
