---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: core-flux-crd
  namespace: flux-system
spec:
  path: "./clusters/titania/flux-crd"
  interval: 10m0s
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
