---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: step-issuer
  namespace: flux-system
spec:
  chart:
    spec:
      chart: step-issuer
      sourceRef:
        kind: HelmRepository
        name: smallstep
      interval: 1m
      version: "0.7.0"
  interval: 1m0s
  targetNamespace: cert-manager
  releaseName: step-issuer
  install:
    remediation:
      retries: -1
  upgrade:
    remediation:
      retries: -1
  values:
    replicaCount: 2
    affinity:
      podAntiAffinity:
        preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 50
            podAffinityTerm:
              topologyKey: kubernetes.io/hostname
              labelSelector:
                matchLabels:
                  app.kubernetes.io/name: step-issuer
